@startuml
!include _style.iuml
title Обработка реакции на подборку
start
:Сообщение пользователя\n(текст или «Выбираю «…»» после\nнажатия на карточку);
:Классифицировать реакцию\n(LLM, ответ из перечня);
switch (Реакция)
case (select)
  if (Фильм определён однозначно?) then (да)
    :save_choice;
    :Подтвердить выбор;
  else (нет)
    :Уточнить, какой фильм;
  endif
case (another)
  if (Пожелание изменилось?) then (да)
    :Новые критерии, find_movies\nс исключением показанных;
  elseif (В пуле есть кандидаты?) then (да)
    :Следующие три из пула;
  else (нет)
    :Ослабить критерии, find_movies;
  endif
  :Три фильма с обоснованием;
case (stop)
  :Завершить подбор;
case (off_topic)
  :Вернуть к подборке;
endswitch
:Сохранить сессию;
stop
@enduml
